import './globals.css';

export const metadata = {
  title: 'Tailwind Practice',
  description: 'Generated by tailwind',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      // className={localStorage.getItem('darkMode') === 'true' ? 'dark' : 'light'}
    >
      <body className="dark:bg-slate-900 dark:text-white">{children} </body>
    </html>
  );
}
